[2025-09-21T12:42:16.903+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-21T12:42:16.927+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: iot_streaming_pipeline.start_kafka_producer manual__2025-09-21T12:37:11.130300+00:00 [queued]>
[2025-09-21T12:42:16.932+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: iot_streaming_pipeline.start_kafka_producer manual__2025-09-21T12:37:11.130300+00:00 [queued]>
[2025-09-21T12:42:16.933+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-09-21T12:42:16.941+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): start_kafka_producer> on 2025-09-21 12:37:11.130300+00:00
[2025-09-21T12:42:16.946+0000] {standard_task_runner.py:63} INFO - Started process 133 to run task
[2025-09-21T12:42:16.950+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'iot_streaming_pipeline', 'start_kafka_producer', 'manual__2025-09-21T12:37:11.130300+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/iot_pipeline_dag.py', '--cfg-path', '/tmp/tmp475dvn2p']
[2025-09-21T12:42:16.952+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask start_kafka_producer
[2025-09-21T12:42:16.967+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-21T12:42:17.013+0000] {task_command.py:426} INFO - Running <TaskInstance: iot_streaming_pipeline.start_kafka_producer manual__2025-09-21T12:37:11.130300+00:00 [running]> on host b539b7bf4f8a
[2025-09-21T12:42:17.078+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='iot_streaming_pipeline' AIRFLOW_CTX_TASK_ID='start_kafka_producer' AIRFLOW_CTX_EXECUTION_DATE='2025-09-21T12:37:11.130300+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-21T12:37:11.130300+00:00'
[2025-09-21T12:42:17.079+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-21T12:42:17.096+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-21T12:42:17.096+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/*** && python kafka_producer/producer.py']
[2025-09-21T12:42:17.103+0000] {subprocess.py:86} INFO - Output:
[2025-09-21T12:42:17.170+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-09-21T12:42:17.171+0000] {subprocess.py:93} INFO -   File "/opt/***/kafka_producer/producer.py", line 1, in <module>
[2025-09-21T12:42:17.171+0000] {subprocess.py:93} INFO -     from kafka import KafkaProducer
[2025-09-21T12:42:17.171+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'kafka'
[2025-09-21T12:42:17.176+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-09-21T12:42:17.176+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-21T12:42:17.185+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-09-21T12:42:17.188+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=iot_streaming_pipeline, task_id=start_kafka_producer, run_id=manual__2025-09-21T12:37:11.130300+00:00, execution_date=20250921T123711, start_date=20250921T124216, end_date=20250921T124217
[2025-09-21T12:42:17.200+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 7 for task start_kafka_producer (Bash command failed. The command returned a non-zero exit code 1.; 133)
[2025-09-21T12:42:17.214+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-09-21T12:42:17.237+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-21T12:42:17.240+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
