[2025-09-21T12:32:41.919+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-21T12:32:41.944+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: iot_streaming_pipeline.start_kafka_producer manual__2025-09-21T12:27:35.510419+00:00 [queued]>
[2025-09-21T12:32:41.950+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: iot_streaming_pipeline.start_kafka_producer manual__2025-09-21T12:27:35.510419+00:00 [queued]>
[2025-09-21T12:32:41.951+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-09-21T12:32:41.958+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): start_kafka_producer> on 2025-09-21 12:27:35.510419+00:00
[2025-09-21T12:32:41.966+0000] {standard_task_runner.py:63} INFO - Started process 91 to run task
[2025-09-21T12:32:41.969+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'iot_streaming_pipeline', 'start_kafka_producer', 'manual__2025-09-21T12:27:35.510419+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/iot_pipeline_dag.py', '--cfg-path', '/tmp/tmp56q81pnm']
[2025-09-21T12:32:41.972+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask start_kafka_producer
[2025-09-21T12:32:41.987+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-21T12:32:42.018+0000] {task_command.py:426} INFO - Running <TaskInstance: iot_streaming_pipeline.start_kafka_producer manual__2025-09-21T12:27:35.510419+00:00 [running]> on host b539b7bf4f8a
[2025-09-21T12:32:42.085+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='iot_streaming_pipeline' AIRFLOW_CTX_TASK_ID='start_kafka_producer' AIRFLOW_CTX_EXECUTION_DATE='2025-09-21T12:27:35.510419+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-21T12:27:35.510419+00:00'
[2025-09-21T12:32:42.089+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-21T12:32:42.102+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-21T12:32:42.109+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 220, in execute
    raise AirflowException(f"Can not find the cwd: {self.cwd}")
airflow.exceptions.AirflowException: Can not find the cwd: /Users/kabirmathur/Documents/AQI
[2025-09-21T12:32:42.112+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=iot_streaming_pipeline, task_id=start_kafka_producer, run_id=manual__2025-09-21T12:27:35.510419+00:00, execution_date=20250921T122735, start_date=20250921T123241, end_date=20250921T123242
[2025-09-21T12:32:42.120+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 5 for task start_kafka_producer (Can not find the cwd: /Users/kabirmathur/Documents/AQI; 91)
[2025-09-21T12:32:42.153+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-09-21T12:32:42.169+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-21T12:32:42.172+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
